FROM ubuntu:14.04

RUN apt-get -y update && \
    apt-get -y install gcc build-essential libgpgme11-dev libassuan-dev && \
    apt-get clean && \
    rm -rf /var/cache/apt/*

WORKDIR /go/src/github.com/authit/client-c

ADD . /go/src/github.com/authit/client-c
